.PHONY: clean help requirements test test-all upgrade

.DEFAULT_GOAL := help

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@perl -nle'print $& if m{^[a-zA-Z_-]+:.*?## .*$$}' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}'

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	coverage erase
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

requirements: ## install development environment requirements
	pip install -qr requirements/pip.txt
	pip install -qr requirements/dev.txt --exists-action w
	pip-sync requirements/dev.txt requirements/private.* requirements/test.txt

test: clean ## run tests in the current virtualenv
	pytest

test-all: ## run tests on every supported Python/Django combination
	tox

quality: ## Run Quality checks
	tox -e quality

COMMON_CONSTRAINTS_TXT=requirements/common_constraints.txt
.PHONY: $(COMMON_CONSTRAINTS_TXT)
$(COMMON_CONSTRAINTS_TXT):
	wget -O "$(@)" https://raw.githubusercontent.com/edx/edx-lint/master/edx_lint/files/common_constraints.txt || touch "$(@)"

upgrade: $(COMMON_CONSTRAINTS_TXT)
	## update the requirements/*.txt files with the latest packages satisfying requirements/*.in
	pip install -qr requirements/pip-tools.txt
	pip-compile --rebuild --upgrade --allow-unsafe -o requirements/pip.txt requirements/pip.in
	pip-compile --rebuild --upgrade -o requirements/pip-tools.txt requirements/pip-tools.in
	pip install -qr requirements/pip.txt
	pip install -qr requirements/pip-tools.txt
	# --allow-unsafe is required here because fs (pyfilesystem2) depends on setuptools
	# (via pkg_resources for namespace package declarations). Without it, pip-compile
	# silently omits setuptools from the output, causing ImportError at runtime.
	# TODO: remove --allow-unsafe once a version of fs is available that does not
	# depend on setuptools/pkg_resources. Track: https://github.com/PyFilesystem/pyfilesystem2/issues/577
	pip-compile --upgrade --allow-unsafe -o requirements/dev.txt requirements/base.in requirements/dev.in
	pip-compile --upgrade --allow-unsafe -o requirements/test.txt requirements/base.in requirements/test.in
	pip-compile --upgrade --allow-unsafe -o requirements/ci.txt requirements/ci.in
	pip-compile --upgrade --allow-unsafe -o requirements/quality.txt requirements/quality.in
	# Let tox control the django version for tests
	sed '/^django==/d' requirements/test.txt > requirements/test.tmp
	mv requirements/test.tmp requirements/test.txt
